Add tests
gnosis/safe-transaction-service pull request #476
Opened 2021-11-09 10:32 UTC by Uxio0

### What was wrong?

Closes #473

### How was it fixed?

@gnosis/safe-services

2021-11-09 16:39 UTC, Uxio0 commented
Getting closer to 90%

2021-11-10 10:12 UTC, fmrsabino requested changes

2021-11-10 10:18 UTC, Uxio0 commented on .coveragerc
> +    @(abc\.)?abstractmethod
Good points. I picked the example from https://coverage.readthedocs.io/en/6.1.1/config.html#syntax

2021-11-10 10:18 UTC, Uxio0 commented on .coveragerc
> +    if 0:
That was on the example configuration :)

2021-11-10 10:19 UTC, Uxio0 commented on .coveragerc
> +    pragma: no cover
To manually exclude stuff (for example, Celery configuration)

2021-11-10 10:20 UTC, Uxio0 commented on .coveragerc
> +    raise NotImplementedError
Maybe is broad on `AssertionError`, but `NotImplemented` error are only for not implemented abstract methods, so it should be always excluded

2021-11-10 10:22 UTC, Uxio0 commented on .coveragerc
> +    raise NotImplementedError
I don't want to go marking abstract methods one by one

2021-11-10 13:29 UTC, fmrsabino approved these changes

2021-11-10 15:46 UTC, merged