support for trusted csrf origins
gnosis/safe-transaction-service pull request #644
Opened 2022-01-19 18:31 UTC by InoMurko

### What was wrong?
Support for CSRF trusted origins https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-trusted-origins
which is useful for different kinds of deployments.
Closes #

### How was it fixed?
Added reading env CSRF_TRUSTED_ORIGINS and setting CSRF_TRUSTED_ORIGINS.  
@gnosis/safe-services

2022-01-19 18:32 UTC, InoMurko commented
I have read the CLA Document and I hereby sign the CLA

2022-01-20 10:46 UTC, Uxio0 requested changes

2022-01-20 10:46 UTC, Uxio0 commented on config/settings/production.py
> +CSRF_TRUSTED_ORIGINS = [
Please use `env.list` 😉 like https://github.com/gnosis/safe-transaction-service/blob/003d19a9f57148e3216cfc2654c64d11743e6bfe/config/settings/local.py#L16

2022-01-20 13:22 UTC, Uxio0 approved these changes

2022-01-20 13:23 UTC, merged